# Generated by Django 2.2.3 on 2020-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200625_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_user',
            name='active',
            field=models.TextField(default=0),
        ),
    ]
