# Generated by Django 3.1.5 on 2021-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_config_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_user',
            name='ip',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
